name: Deployment Pipeline
on:
  push:
    branches:
      - main
env:
  SEED: ${{secrets.SEED}}
  EXPIRATION_TOKEN: ${{secrets.SEED}}
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
          npm install -D
      - name: run Lint
        run: npm run lint
      - name: run Test
        run: npm run test
      - name: run Build
        run: npm run build
